### ISSUE TITLE
App fails to build with the latest Flutter

### ISSUE THREAD

**Issue by Vaibhavyy** [optimalstrategy/sms_forwarder_app#1]
I am not able to build it with android studio and flutter.

Tell me how i can do

Pls help
https://t.me/frwdmess
Contact me..

**Comment by optimalstrategy** [comment]
Hello,

I've updated the app. It should now build with the latest flutter and dart versions. Please follow the instructions on [this page](https://flutter.dev/docs/deployment/android) in order to build it yourself.

Alternatively, you can download the latest release [here](https://github.com/optimalstrategy/sms_forwarder_app/releases/tag/v1.2.0).
